spring:
  application:
    name: sky-codechallange
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jackson:
    json:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        fail-on-unknown-properties: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
